version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    groups:
      node-dev-dependencies:
        dependency-type: "development"
    commit-message:
      prefix: "deps"
      include: "scope"
